from __future__ import annotations

import logging
from typing import Optional

import pandas as pd
import spotipy

logger = logging.getLogger(__name__)


def get_library_tracks_for_cluster(
    df_clustered: pd.DataFrame,
    cluster_index: int,
    limit: int = 30,
) -> list[str]:
    """Return spotify_track_ids for the cluster in random order."""
    cluster_df = df_clustered[df_clustered["cluster"] == cluster_index]
    return cluster_df["spotify_track_id"].sample(frac=1).tolist()[:limit]


def build_playlist(
    df_clustered: pd.DataFrame,
    cluster_index: int,
    target_size: int = 30,
) -> list[str]:
    """Return up to target_size randomly ordered track IDs from the mood cluster."""
    return get_library_tracks_for_cluster(df_clustered, cluster_index, limit=target_size)


def create_or_replace_playlist(
    sp: spotipy.Spotify,
    user_spotify_id: str,
    track_ids: list[str],
    label: str,
    playlist_name: Optional[str] = None,
) -> str:
    """
    Find or create a playlist named after the mood label, replace its tracks,
    and return the Spotify playlist URL.
    """
    name = playlist_name or f"Mood Engine: {label}"

    playlist_id: Optional[str] = None
    playlists = sp.current_user_playlists(limit=50)
    while playlists:
        for pl in playlists["items"]:
            if pl["name"] == name and pl["owner"]["id"] == user_spotify_id:
                playlist_id = pl["id"]
                break
        if playlist_id or not playlists.get("next"):
            break
        playlists = sp.next(playlists)

    if not playlist_id:
        created = sp.user_playlist_create(
            user_spotify_id,
            name,
            public=False,
            description="Generated by Spotify Mood Engine",
        )
        playlist_id = created["id"]

    sp.playlist_replace_items(playlist_id, [])
    for i in range(0, len(track_ids), 100):
        sp.playlist_add_items(playlist_id, track_ids[i : i + 100])

    logger.info("Playlist '%s' updated with %d tracks", name, len(track_ids))
    return f"https://open.spotify.com/playlist/{playlist_id}"
